project:
  type: website
  resources:
    - cv.pdf

website:
  title: "Matheus Zanetti"
  site-url: https://matheuszanetti.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
      - href: cv.pdf
        text: CV
      - href: contact/index.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source
